import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import Background from "@/components/background";
import { Toaster } from "sonner";

const inter = Inter({ subset: ["latin"]});

export const metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className} transition-colors duration-300`}
      >
        {/* header */}
        <Header />
        <Background>
          <main className="min-h-screen">
            {children}
          </main>
        </Background>
        <Toaster richColors />
        {/* footer */}
        <footer className="bg-blue-50 py-12">
          <div className="container mx-auto px-4 text-center text-gray-600">
            <p>made this app</p>
          </div>
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
